server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
                ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:test"
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
server:
    port: 9000
